name: CI/CD Pipeline for AtyBackend on Ubuntu 22.04

on:
  push:
    branches:
      - vgff-ci-cd  # O nome da branch que dispara o CI/CD


jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'
        
    - name: SSH into remote server
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        ssh -i private_key ${{ secrets.USER }}@${{ secrets.HOST }} << 'ENDSSH'
        
        
          cd /home/aty/aty-backend  
          git pull origin staging
          
          
          fuser -k 5121/tcp || echo "No process running on port 5121"
          
          
          cd /home/aty/aty-backend/src/AtyBackend.Infrastructure.Data  
          dotnet ef database update
          
          
          cd /home/aty/aty-backend/src/AtyBackend.API  
          nohup dotnet run > run.log 2> run.err < /dev/null &

        ENDSSH
